### ISSUE TITLE
Python 2.7.15 install fail

### ISSUE THREAD

**Issue by welbo97** [Peter-Slump/python-keycloak-client#16]
Trying to install with pip2.7 on a Centos 6 machine. 
`pip2.7 install -Iv https://github.com/Peter-Slump/python-keycloak-client/archive/v0.2.2.zip`

Possibly a distutils version issue?

Returns error code 1 with:
```     Running command python setup.py egg_info
    /usr/local/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    zip_safe flag not set; analyzing archive contents...

    Installed /tmp/pip-req-build-elsdTF/.eggs/pytest_runner-4.4-py2.7.egg
    error in python-keycloak-client setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
Cleaning up...
  Removing source in /tmp/pip-req-build-elsdTF
Removed https://github.com/Peter-Slump/python-keycloak-client/archive/v0.2.2.zip from build tracker '/tmp/pip-req-tracker-7np39i'
Removed build tracker '/tmp/pip-req-tracker-7np39i'
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-elsdTF/
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 315, in run
    resolver.resolve(requirement_set)
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 349, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 158, in prep_for_dist
    self.req.prepare_metadata()
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 530, in prepare_metadata
    self.run_egg_info()
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 609, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/utils/misc.py", line 761, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-elsdTF/ ```

**Comment by nkoshell** [comment]
Hello @welbo97, please tell me which `pip2.7` version you are using?

**Comment by welbo97** [comment]
``` pip2.7 -V
pip 19.0.3 from /usr/local/lib/python2.7/site-packages/pip (python 2.7)
```

The installation came from a package install with a `requirement.txt` file to load dependencies, including:
`python-keycloak-client == 0.2.2`

**Comment by nkoshell** [comment]
Ok, your version `setuptools` must be `>=20.2`. For same reasons
